import { 
  Profile, 
  Experience, 
  Education, 
  SkillCategory, 
  Skill, 
  Service, 
  ContentCategory,
  Project, 
  GalleryImage, 
  BlogPost, 
  SocialLink, 
  SiteSetting, 
  ContactMessage,
  AuditLog 
} from '../types';

export const initialProfile: Profile = {
  id: 'profile_1',
  name: 'Gunjan Shrestha',
  dateOfBirth: '1998-05-15',
  address: 'Kathmandu, Bagmati Province, Nepal',
  headline: 'Multidisciplinary Founder & Operator — Operations, Finance, Tech & Design',
  shortBio: 'Multidisciplinary founder and operator based in Kathmandu, focused on building businesses that can scale beyond local markets and operate at an international level.',
  longBio: 'I believe people are defined by their work and their commitment to continuous improvement—learning from mistakes, taking responsibility, and consistently raising the bar. My background spans founding and operating ventures from the ground up: managing technology stacks, brand design, custom fine jewellery craftsmanship, and end-to-end digital strategies, alongside leading office operations, financial accounts, reporting, and cross-functional teams in software development and UI design.\n\nAlongside this, I have built extensive expertise in accounting, company auditing, and the legal and compliance frameworks required to run well-structured businesses. My focus is expanding this to international standards to build and scale multinational ventures combining strong operations, sound financial governance, and thoughtful brand strategy.',
  profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
  visitingCardImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
  email: 'gunjanstha01@gmail.com',
  alternateEmail: 'contact@gunjanshrestha.com.np',
  primaryEmailLabel: 'Direct & Official',
  alternateEmailLabel: 'Advisory & Ventures',
  phone: '+977 9800000000',
  secondaryPhone: '+977 9811111111',
  phoneDisplayOption: 'both',
  whatsappNumber: 'primary',
  location: 'Kathmandu, Nepal',
  website: 'https://www.gunjanshrestha.com.np',
  languagesSpoken: ['English (Fluent / Professional)', 'Nepali (Native)', 'Hindi (Conversational)'],
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-08-27T00:00:00.000Z',
};

export const initialExperiences: Experience[] = [
  {
    id: 'exp_1',
    category: 'Operations & Management',
    title: 'Operations, Accounts & Cross-Functional Management',
    roleTitle: 'Operations Manager & Financial Accountant',
    organization: 'Technology & Systems Enterprise',
    location: 'Kathmandu, Nepal',
    startDate: '2023',
    isCurrent: true,
    shortDescription: 'Leading office operations, logistics, accounting, financial reporting, and cross-functional software/design execution.',
    description: 'Shaping how the enterprise runs and scales. Work spans office operations, logistical systems, financial ledgers, compliance reporting, and steering cross-functional initiatives across software development, digital graphics, and UI/UX design workflows.',
    tags: ['Operations', 'Financial Accounting', 'Reporting', 'Cross-Functional Leadership', 'Logistics', 'Software & UI'],
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    featured: true,
    displayOrder: 1,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-27T00:00:00.000Z',
  },
  {
    id: 'exp_2',
    category: 'Venture Founding',
    title: 'Venture Founder & Operational Lead',
    roleTitle: 'Founder & Creative/Operational Director',
    organization: 'Fine Jewellery & Brand Venture',
    location: 'Kathmandu, Nepal',
    startDate: '2020',
    endDate: '2023',
    isCurrent: false,
    shortDescription: 'Full operational management, technology stack, brand design, digital presence, legal/financial governance, and fine custom jewellery design.',
    description: 'Served as the operational brain behind the business. Managed the technology stack, brand identity, and complete digital presence—including social media strategy, content creation, and product photography. Handled company legal and financial governance while leading custom design and production in silver, gold, and pearls.',
    tags: ['Venture Building', 'Jewellery Design', 'Gold & Silver', 'Tech Stack', 'Brand Strategy', 'Product Photography', 'Legal & Finance'],
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
    featured: true,
    displayOrder: 2,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-27T00:00:00.000Z',
  },
  {
    id: 'exp_3',
    category: 'Creative Direction',
    title: 'Graphic Design & Social Media Strategy',
    roleTitle: 'Brand Designer & Digital Strategist (4+ Years)',
    organization: 'Commercial Brand & Media Group',
    location: 'Nepal',
    startDate: '2019',
    endDate: '2023',
    isCurrent: false,
    shortDescription: 'Over four years directing brand visuals, social media management, campaign creative, and online digital presence.',
    description: 'Spent over four years steering graphic design and social media management across commercial entities, producing comprehensive brand visuals, marketing collaterals, digital campaigns, and establishing cohesive online identity.',
    tags: ['Graphic Design', 'Social Media Management', 'Brand Visuals', 'Campaign Strategy', 'Digital Presence'],
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop',
    featured: true,
    displayOrder: 3,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-27T00:00:00.000Z',
  },
  {
    id: 'exp_4',
    category: 'Financial Governance',
    title: 'Accounting, Auditing & Legal Compliance',
    roleTitle: 'Auditing & Compliance Specialist',
    organization: 'Corporate Governance & Auditing Practice',
    location: 'Nepal',
    startDate: '2021',
    isCurrent: true,
    shortDescription: 'Deep expertise in accounting, company auditing, statutory regulations, and legal compliance frameworks.',
    description: 'Built extensive practical knowledge in corporate accounting, company auditing, tax standards, and legal compliance frameworks required to run a compliant, well-structured business in Nepal. Currently expanding this expertise to international standards for cross-border and multinational scalability.',
    tags: ['Corporate Accounting', 'Company Auditing', 'Legal Frameworks', 'Statutory Compliance', 'Financial Governance'],
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=800&auto=format&fit=crop',
    featured: true,
    displayOrder: 4,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-27T00:00:00.000Z',
  },
  {
    id: 'exp_5',
    category: 'Global Strategy',
    title: 'Scalable Ventures & Cross-Border Expansion',
    roleTitle: 'Venture Architect & Operator',
    organization: 'International Business Strategy',
    location: 'Kathmandu, Nepal',
    startDate: '2023',
    isCurrent: true,
    shortDescription: 'Applying strong operational systems, sound financial governance, and brand strategy toward scalable multinational ventures.',
    description: 'Focused on building and scaling ventures that can transcend local boundaries and operate competitively on an international level. Actively connecting with founders, investors, and operators on cross-border business architectures.',
    tags: ['Cross-Border Business', 'Multinational Strategy', 'Operational Scale', 'Governance', 'Brand Strategy'],
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    featured: true,
    displayOrder: 5,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-27T00:00:00.000Z',
  }
];

export const initialEducations: Education[] = [
  {
    id: 'edu_1',
    institution: 'Tribhuvan University Affiliated Institute',
    qualification: 'Bachelor in Information Technology / Computer Studies',
    field: 'Information Technology & Software Engineering',
    location: 'Kathmandu, Nepal',
    startDate: '2020',
    endDate: '2024',
    description: 'Rigorous academic curriculum covering algorithmic thinking, software architecture, data structures, network protocols, database engineering, and web development fundamentals.',
    displayOrder: 1,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'edu_2',
    institution: 'Higher Secondary Education Board (HSEB)',
    qualification: 'Higher Secondary School Certificate (+2)',
    field: 'Management, Business Studies & Accounting',
    location: 'Nepal',
    startDate: '2018',
    endDate: '2020',
    description: 'Comprehensive study of accounting principles, financial management, business mathematics, economics, and commercial law foundations.',
    displayOrder: 2,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialSkillCategories: SkillCategory[] = [
  {
    id: 'cat_tech',
    name: 'Technology & Systems',
    slug: 'technology',
    description: 'Core programming languages, backend runtimes, database designs, and system architectures.',
    displayOrder: 1,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'cat_design',
    name: 'Design & Visual Communication',
    slug: 'design',
    description: 'Interface design, visual balance, design tokenization, typography, and user experience.',
    displayOrder: 2,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'cat_biz',
    name: 'Business, Finance & Operations',
    slug: 'business',
    description: 'Practical business management, precious metals trading operations, bookkeeping, and process digitization.',
    displayOrder: 3,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialSkills: Skill[] = [
  // Technology
  { id: 'sk_1', categoryId: 'cat_tech', name: 'Information Technology', slug: 'information-technology', description: 'Systems administration, networking essentials, and technical workflow architecture.', displayOrder: 1, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_2', categoryId: 'cat_tech', name: 'Web Technologies', slug: 'web-technologies', description: 'Semantic HTML5, CSS3, modern JavaScript (ESNext), and DOM architecture.', displayOrder: 2, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_3', categoryId: 'cat_tech', name: 'Software Design & React / TypeScript', slug: 'software-design', description: 'Component lifecycles, state modeling, type safety, and modular frontend architectures.', displayOrder: 3, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_4', categoryId: 'cat_tech', name: 'Backend Development & APIs', slug: 'backend-dev', description: 'Node.js, Express, RESTful architecture, session security, and request validation pipelines.', displayOrder: 4, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_5', categoryId: 'cat_tech', name: 'Databases & Relational Schema', slug: 'databases', description: 'PostgreSQL, Prisma ORM, entity-relationship modeling, migrations, and transactional integrity.', displayOrder: 5, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_6', categoryId: 'cat_tech', name: 'Systems & Infrastructure', slug: 'systems', description: 'Linux server fundamentals, environment controls, reverse proxies, and deployment flows.', displayOrder: 6, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },

  // Design
  { id: 'sk_7', categoryId: 'cat_design', name: 'Graphic Design', slug: 'graphic-design', description: 'Visual balance, brand assets, vector illustration, and print/digital collateral.', displayOrder: 1, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_8', categoryId: 'cat_design', name: 'UI / Interface Design', slug: 'ui-design', description: 'Clean layouts, high contrast ratios, design tokens, responsive breakpoints, and component states.', displayOrder: 2, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_9', categoryId: 'cat_design', name: 'UX & Information Hierarchy', slug: 'ux-design', description: 'User mental models, friction removal, intuitive navigation trees, and accessibility.', displayOrder: 3, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_10', categoryId: 'cat_design', name: 'Visual Communication & Editorial', slug: 'visual-comm', description: 'Expressive typography pairing, restrained palettes, and editorial layout rhythm.', displayOrder: 4, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_11', categoryId: 'cat_design', name: 'Branding & Identity', slug: 'branding', description: 'Cohesive brand narratives, logo guidelines, and consistent design token systems.', displayOrder: 5, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },

  // Business
  { id: 'sk_12', categoryId: 'cat_biz', name: 'Business Operations', slug: 'business-operations', description: 'Operational workflows, inventory logistics, client service protocols, and administrative execution.', displayOrder: 1, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_13', categoryId: 'cat_biz', name: 'Accounting & Bookkeeping', slug: 'accounting', description: 'General ledger maintenance, voucher posting, balance reconciliation, and VAT tracking basics.', displayOrder: 2, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_14', categoryId: 'cat_biz', name: 'Business Finance', slug: 'business-finance', description: 'Working capital management, margin evaluations, pricing models, and cashflow projections.', displayOrder: 3, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_15', categoryId: 'cat_biz', name: 'Jewellery & Precious Metals Trade', slug: 'jewellery-business', description: 'Gold & silver purity testing protocols, karat calculations, hallmark practices, and bullion market transactions.', displayOrder: 4, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
  { id: 'sk_16', categoryId: 'cat_biz', name: 'Business Planning & Process Digitization', slug: 'business-planning', description: 'Translating manual pen-and-paper commercial practices into reliable software solutions.', displayOrder: 5, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-26T00:00:00.000Z' },
];

export const initialServices: Service[] = [
  {
    id: 'srv_1',
    title: 'Website & Interface Design',
    slug: 'website-interface-design',
    shortDescription: 'Bespoke, editorial-grade web designs with high typographic contrast and seamless responsiveness.',
    description: 'I design custom websites and interfaces that move away from generic SaaS templates. Every layout is crafted with mathematical spacing, intentional typography, dark/light contrast balance, and purposeful interaction design.',
    icon: 'Layout',
    displayOrder: 1,
    featured: true,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'srv_2',
    title: 'UI/UX Design & Prototyping',
    slug: 'ui-ux-design',
    shortDescription: 'User journeys, wireframing, interactive prototypes, and design-system tokenization.',
    description: 'Transforming ambiguous product concepts into clean, predictable user experiences. I map user flows, build functional wireframes, and establish consistent design-token architectures ready for engineering implementation.',
    icon: 'Layers',
    displayOrder: 2,
    featured: true,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'srv_3',
    title: 'Graphic & Visual Communication',
    slug: 'graphic-design',
    shortDescription: 'Brand identity assets, typographic systems, promotional graphics, and visual guidelines.',
    description: 'Crafting distinct visual communication materials that elevate your brand narrative, including logo marks, brand guidelines, editorial decks, and custom vector collateral.',
    icon: 'PenTool',
    displayOrder: 3,
    featured: true,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'srv_4',
    title: 'Web Application Development',
    slug: 'web-application-development',
    shortDescription: 'Full-stack React, TypeScript, and server-side architectures built for speed and maintainability.',
    description: 'Building robust, modern web applications with clean component boundaries, database-backed CMS engines, and secure authentication models that scale smoothly over time.',
    icon: 'Code2',
    displayOrder: 4,
    featured: true,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'srv_5',
    title: 'Business Process Digitization',
    slug: 'business-process-digitization',
    shortDescription: 'Consulting on transitioning manual workflows, retail operations, and ledgers into digital tools.',
    description: 'Leveraging direct commercial trade experience to identify operational bottlenecks in physical businesses and architect pragmatic, low-friction digital tools for inventory, invoices, and recordkeeping.',
    icon: 'TrendingUp',
    displayOrder: 5,
    featured: false,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'srv_6',
    title: 'IT & Technology Consultation',
    slug: 'it-consultation',
    shortDescription: 'Strategic advice on software choices, web hosting infrastructure, and digital presence.',
    description: 'Grounded technical guidance for small businesses and individuals looking to establish a credible digital presence without overpaying for bloated agency retainers or unnecessary cloud infrastructure.',
    icon: 'ShieldCheck',
    displayOrder: 6,
    featured: false,
    published: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialContentCategories: ContentCategory[] = [
  { id: 'cat_1', name: 'Software & Business Solutions', slug: 'software-business-solutions', type: 'CASE_STUDY', description: 'Internal engines, transaction ledgers, and operational software platforms.', displayOrder: 1, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_2', name: 'Web Design & Architecture', slug: 'web-design-architecture', type: 'CASE_STUDY', description: 'Bespoke web applications, digital identity platforms, and modern frontend architecture.', displayOrder: 2, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_3', name: 'Brand & Visual Design', slug: 'brand-visual-design', type: 'CASE_STUDY', description: 'Typography, brand identity, vector design systems, and art direction.', displayOrder: 3, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_4', name: 'Software Design', slug: 'software-design', type: 'CASE_STUDY', description: 'Point-of-sale systems, compliance calculation tools, and user interaction design.', displayOrder: 4, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_5', name: 'Design Systems & Tokens', slug: 'design-systems-tokens', type: 'CASE_STUDY', description: 'Monochrome token architectures, spacing scales, and WCAG AA contrast standards.', displayOrder: 5, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_6', name: 'Design & Philosophy', slug: 'design-philosophy', type: 'JOURNAL', description: 'Essays on software architecture, interface restraint, and intentional engineering.', displayOrder: 6, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_7', name: 'Business & Technology', slug: 'business-technology', type: 'JOURNAL', description: 'Lessons bridging precious metals commerce, gold trading, and software rigor.', displayOrder: 7, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_8', name: 'Business & Operations', slug: 'business-operations', type: 'JOURNAL', description: 'Practical observations on emerging market realities, trade, and digitizing family enterprise.', displayOrder: 8, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_9', name: 'Design & Visual Hierarchy', slug: 'design-visual-hierarchy', type: 'JOURNAL', description: 'Disciplined typographic scale, high-density layout math, and subtractive visual design.', displayOrder: 9, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_10', name: 'Finance & Operations', slug: 'finance-operations', type: 'JOURNAL', description: 'High-value commodity inventory management, bullion accounting, and risk auditing.', displayOrder: 10, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_11', name: 'Workspaces & Hardware', slug: 'workspaces-hardware', type: 'GALLERY', description: 'Development setups, analog tools, and workshop environments.', displayOrder: 11, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_12', name: 'Typography & Interface', slug: 'typography-interface', type: 'GALLERY', description: 'Visual tokens, micro-interactions, and design systems.', displayOrder: 12, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
  { id: 'cat_13', name: 'Art Direction & Print', slug: 'art-direction-print', type: 'GALLERY', description: 'Physical print collateral, branding assets, and photography.', displayOrder: 13, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-31T00:00:00.000Z' },
];

export const initialProjects: Project[] = [
  {
    id: 'proj_1',
    title: 'Gold & Silver Trade Ledger Engine',
    slug: 'gold-silver-trade-ledger',
    category: 'Software & Business Solutions',
    shortSummary: 'A dedicated internal ledger and daily bullion price tracker customized for traditional Nepalese jewellery operations.',
    overview: 'In traditional Nepalese jewellery commerce, daily fluctuating gold and silver rates, purity variations (Tola, Grams, Lal), and customer buy-backs create immense ledger overhead when handled manually.',
    problem: 'Retail managers relied on physical notebooks prone to calculation errors, missing historical transaction trails, and difficult year-end reconciliations.',
    approach: 'I architected a lightweight, secure web ledger system tailored specifically to bullion units and karat conversion formulas with instant daily rate calculation.',
    design: 'High-contrast numeric displays with dark theme readability for indoor counter lighting and large interactive keypad triggers.',
    technology: 'TypeScript, React, Node.js, SQLite/PostgreSQL, Tailwind CSS, Local Storage cache for offline trade reliability.',
    result: 'Reduced daily transaction closing time from 45 minutes to under 5 minutes with zero rate miscalculation incidents.',
    heroImage: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?q=80&w=1200&auto=format&fit=crop',
    images: [
      { id: 'pimg_1_1', url: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?q=80&w=1000&auto=format&fit=crop', altText: 'Gold and silver bars representing precious metals trade', caption: 'Precious metal trading calculations interface mockup', displayOrder: 1 },
      { id: 'pimg_1_2', url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?q=80&w=1000&auto=format&fit=crop', altText: 'Ledger financial analytics table', caption: 'Transaction ledger records and automated daily reconciliation', displayOrder: 2 },
    ],
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
    published: true,
    displayOrder: 1,
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'proj_2',
    title: 'Gunjan Shrestha Digital Identity Platform',
    slug: 'gunjan-shrestha-platform',
    category: 'Web Design & Architecture',
    shortSummary: 'A bespoke, dark-first personal digital identity platform and private content management system.',
    overview: 'This project is the complete realization of a production-ready personal platform bridging professional journey, design work, and business experiences.',
    problem: 'Traditional portfolios are either static resume dumps or bloated templates with generic visual clichés like glowing neon badges and fake skill percentage bars.',
    approach: 'Designed from first principles using an editorial typography scale, hybrid vertical timeline, and an isolated single-admin CMS architecture.',
    design: 'Near-black #080808 background, warm metallic accents (#C6A87D), generous negative space, and strict WCAG AA contrast standards.',
    technology: 'Next.js / React, TypeScript, Tailwind CSS, Express API, Motion transitions, PostgreSQL / Prisma Schema.',
    result: 'Sub-second load times, pristine mobile responsiveness across 320px–1920px+, and effortless content management without touching code.',
    heroImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    images: [
      { id: 'pimg_2_1', url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1000&auto=format&fit=crop', altText: 'Clean editorial workspace layout', caption: 'Minimalist desktop wireframe and typography system', displayOrder: 1 },
      { id: 'pimg_2_2', url: 'https://images.unsplash.com/photo-1522542550221-31fd19575a2d?q=80&w=1000&auto=format&fit=crop', altText: 'Mobile interface layout preview', caption: 'First-class mobile responsiveness & hybrid timeline adaptation', displayOrder: 2 },
    ],
    liveUrl: 'https://www.gunjanshrestha.com.np',
    githubUrl: '#',
    featured: true,
    published: true,
    displayOrder: 2,
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'proj_3',
    title: 'Aura Fine Jewellery Brand & Visual Identity',
    slug: 'aura-jewellery-identity',
    category: 'Brand & Visual Design',
    shortSummary: 'Comprehensive visual identity, typographic guidelines, and packaging design for an artisanal gold craft atelier.',
    overview: 'Artisanal jewellery requires a branding language that balances historic craftsmanship with contemporary luxury minimalism.',
    problem: 'The atelier lacked a coherent identity across physical certificate cards, packaging boxes, and digital product lookbooks.',
    approach: 'Developed an elegant wordmark with bespoke ligatures, accompanied by a muted bronze and warm sand palette that allows the gold pieces to shine.',
    design: 'Serif display headings paired with clean geometric sans body typography and minimalist embossed packaging details.',
    technology: 'Adobe Creative Suite, Figma Design Tokens, Vector Asset Optimization.',
    result: 'Enhanced perceived brand value by over 40% and established a unified design identity across both showroom and digital lookbooks.',
    heroImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop',
    images: [
      { id: 'pimg_3_1', url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop', altText: 'Artisanal gold earrings and gemstone jewellery', caption: 'Jewellery visual catalog and photography direction', displayOrder: 1 },
    ],
    liveUrl: '#',
    featured: true,
    published: true,
    displayOrder: 3,
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'proj_4',
    title: 'Nepal Retail VAT & Transaction Invoicing Tool',
    slug: 'nepal-retail-vat-invoice',
    category: 'Software Design',
    shortSummary: 'A fast, lightweight point-of-sale invoice generator complying with Nepalese Inland Revenue Department guidelines.',
    overview: 'Local micro-enterprises often struggle with heavy billing software that requires constant internet access and complex subscription renewals.',
    problem: 'Small retail merchants need quick bilingual invoice generation (Nepali/English) with automatic 13% VAT calculation without clunky hardware.',
    approach: 'Created an offline-first browser application with thermal printer ESC/POS export and one-click PAN verification formatting.',
    design: 'Clean, dense interface optimized for rapid keyboard data entry (Tab-to-next, Enter-to-print).',
    technology: 'React, TypeScript, Web Print API, IndexedDB local storage.',
    result: 'Adopted by 10+ local merchants to generate over 15,000 compliant receipts with zero downtime.',
    heroImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
    images: [
      { id: 'pimg_4_1', url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1000&auto=format&fit=crop', altText: 'Financial calculations and invoices', caption: 'Rapid keyboard invoicing view', displayOrder: 1 },
    ],
    liveUrl: '#',
    featured: true,
    published: true,
    displayOrder: 4,
    createdAt: '2026-04-10T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'proj_5',
    title: 'Monochrome Design System & Tokens Architecture',
    slug: 'monochrome-design-tokens-architecture',
    category: 'Design Systems & Tokens',
    shortSummary: 'An intentional, high-contrast monochrome design token system built for high-density analytical and editorial interfaces.',
    overview: 'Modern SaaS products suffer from visual noise, non-functional neon glows, and erratic spacing scales that degrade cognitive focus.',
    problem: 'Teams struggle with fragmented CSS files, inconsistent padding ratios, and uncalibrated light/dark mode contrast boundaries.',
    approach: 'Engineered an accessible mathematical scale with 1.125 Major Second step ratios, strict WCAG AA contrast, and modular token variables.',
    design: 'Deep charcoal background (#080808) with warm metallic bronze (#C6A87D) accents and disciplined typographic hierarchy.',
    technology: 'TypeScript, Tailwind CSS, Radix UI primitives, Motion physics, CSS Custom Properties.',
    result: 'Implemented across multiple digital platforms with 100% lighthouse accessibility scores and zero visual regressions.',
    heroImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop',
    images: [
      { id: 'pimg_5_1', url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1000&auto=format&fit=crop', altText: 'Clean code and design token structure', caption: 'Design tokens and typography configuration layout', displayOrder: 1 },
    ],
    liveUrl: '#',
    featured: true,
    published: true,
    displayOrder: 5,
    createdAt: '2026-05-20T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialGalleryImages: GalleryImage[] = [
  {
    id: 'gal_1',
    url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    altText: 'Clean technological hardware and circuit architecture',
    caption: 'Exploring hardware foundations and digital system structures.',
    category: 'Technology',
    width: 1200,
    height: 800,
    featured: true,
    published: true,
    displayOrder: 1,
    createdAt: '2026-01-05T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'gal_2',
    url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop',
    altText: 'Gold crafting workbench and jewellery tools',
    caption: 'Traditional jewellery craftsmanship: gold forming, measurement and precision trade.',
    category: 'Business & Craft',
    width: 1200,
    height: 800,
    featured: true,
    published: true,
    displayOrder: 2,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'gal_3',
    url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    altText: 'Minimalist creative design workspace with warm ambient light',
    caption: 'Quiet workspace dedicated to typography, interface systems, and architecture.',
    category: 'Design',
    width: 1200,
    height: 800,
    featured: true,
    published: true,
    displayOrder: 3,
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'gal_4',
    url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1200&auto=format&fit=crop',
    altText: 'Kathmandu Valley architecture and urban environment',
    caption: 'Kathmandu, Nepal — the vibrant economic backdrop shaping local market insights.',
    category: 'Perspective',
    width: 1200,
    height: 900,
    featured: true,
    published: true,
    displayOrder: 4,
    createdAt: '2026-02-20T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'gal_5',
    url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop',
    altText: 'Source code editor displaying structured TypeScript architecture',
    caption: 'Refining data structures and component boundaries in modern TypeScript.',
    category: 'Technology',
    width: 1200,
    height: 800,
    featured: false,
    published: true,
    displayOrder: 5,
    createdAt: '2026-03-05T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'gal_6',
    url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop',
    altText: 'Financial ledgers, calculation sheets, and fountain pen',
    caption: 'Balancing transaction ledgers and understanding the monetary realities of enterprise.',
    category: 'Finance',
    width: 1200,
    height: 800,
    featured: false,
    published: true,
    displayOrder: 6,
    createdAt: '2026-03-18T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialBlogPosts: BlogPost[] = [
  {
    id: 'post_1',
    title: 'Why I Prefer Building Systems Over Screens',
    slug: 'why-i-prefer-building-systems-over-screens',
    excerpt: 'An exploration of why software value emerges not from isolated UI mockups, but from the coherent interplay of data models, user friction, and real-world workflows.',
    coverImageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    category: 'Design & Philosophy',
    tags: ['Systems', 'UI/UX', 'Software Architecture', 'Design Thinking'],
    readingTime: 6,
    publishedAt: '2026-04-12T00:00:00.000Z',
    status: 'PUBLISHED',
    featured: true,
    seoTitle: 'Why I Prefer Building Systems Over Screens — Gunjan Shrestha',
    seoDescription: 'Thoughts on designing cohesive systems rather than superficial visual mockups.',
    content: `When developers and designers first begin a project, the temptation is almost always to jump directly into high-fidelity canvas tools or component libraries. We want to see buttons, gradients, and animated cards immediately.

However, after spending time managing actual physical business operations and later architecting software products, one truth becomes undeniable:

> **A beautiful screen with a fragile data model is a liability. A resilient system with a clear purpose creates enduring value.**

### The Illusion of Isolated UI

In real-world commerce — whether running a jewellery trade or delivering a customer web portal — the user interface is merely the surface tension of a much deeper pool. Behind every field lies:
- Transaction integrity and state transitions
- Error boundaries and graceful degradation
- Cognitive load on the person sitting at the terminal
- Business constraints that cannot be designed away

When we design systems first, we start with the data contract: *What information exists? Who is authorized to change it? What happens when network connectivity degrades?* Once those questions are answered mathematically, the visual layout follows with natural authority.

### The Restraint of Minimalism

Minimalism is not the absence of effort; it is the deliberate refusal to hide systemic weaknesses behind decorative clutter. In this platform, every spacing token, font pairing, and database entity serves a singular purpose: communicating reality clearly.`,
    createdAt: '2026-04-10T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'post_2',
    title: 'What the Jewellery Business Taught Me About Software Engineering',
    slug: 'what-jewellery-business-taught-me-about-software',
    excerpt: 'Lessons in precious metals, exact fractions, human trust, and why zero-error tolerance in gold trading translates directly into robust code.',
    coverImageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1200&auto=format&fit=crop',
    category: 'Business & Technology',
    tags: ['Jewellery', 'Finance', 'Precision', 'Operations', 'Mindset'],
    readingTime: 8,
    publishedAt: '2026-05-02T00:00:00.000Z',
    status: 'PUBLISHED',
    featured: true,
    seoTitle: 'What the Jewellery Business Taught Me About Software — Gunjan Shrestha',
    seoDescription: 'Bridging physical commercial gold trade discipline with digital software engineering.',
    content: `In the gold and silver trade, there is no room for "approximate" math. If you miscalculate a transaction by a single *Lal* (0.1166 grams of gold), or mistake 22-karat purity for 24-karat, the financial loss is immediate and irreversible.

When I transitioned deeper into Information Technology and Software Design, I noticed an interesting pattern: many software teams treat bugs, floating point inaccuracies, and loose validation as inevitable facts of life. 

Working in physical bullion taught me a very different standard:

### 1. Precision at the Boundary
In gold trading, you inspect the raw material before it enters the furnace. In web development, you must validate input strictly on the server before it touches your database. Client-side validation is a cosmetic convenience; server-side validation is solvency.

### 2. Trust is Fragile
Customers walk into a jewellery showroom with hard-earned savings. They trust your scale and your hallmark. In digital software, visitors trust you with their data, their passwords, and their attention. Once breached by spam, leaks, or deceptive dark patterns, that trust is gone forever.

### 3. Simplicity Survives Stress
During peak festive shopping seasons in Nepal (such as Dhanteras or Tihar), the showroom floor is packed. Complicated software tools collapse under pressure. The only tools that succeed are fast, intuitive, and rock-solid.`,
    createdAt: '2026-04-28T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'post_3',
    title: 'Navigating the Nepalese Business Landscape Through a Digital Lens',
    slug: 'navigating-nepalese-business-landscape-digital-lens',
    excerpt: 'Observations on digitizing traditional family enterprises, local regulatory practicalities, and building software that fits the local market reality.',
    coverImageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1200&auto=format&fit=crop',
    category: 'Business & Operations',
    tags: ['Nepal', 'Business Environment', 'Digitization', 'Finance'],
    readingTime: 5,
    publishedAt: '2026-06-18T00:00:00.000Z',
    status: 'PUBLISHED',
    featured: true,
    seoTitle: 'Navigating the Nepalese Business Landscape — Gunjan Shrestha',
    seoDescription: 'A pragmatic look at software adoption and business operations in Nepal.',
    content: `Building technology in emerging markets like Nepal requires more than importing Silicon Valley frameworks. It demands a thorough understanding of domestic banking limitations, tax compliance (such as PAN/VAT invoicing), cash flow cycles, and family enterprise hierarchies.

When software respects local workflows rather than forcing unnatural corporate friction, adoption happens effortlessly.`,
    createdAt: '2026-06-15T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'post_4',
    title: 'The Art of Restraint: Why Purposeful UI Design Says No',
    slug: 'art-of-restraint-purposeful-ui-design',
    excerpt: 'Examining why subtractive visual design, high-contrast monochrome tokens, and disciplined typographic rhythm outperform decorative clutter.',
    coverImageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    category: 'Design & Visual Hierarchy',
    tags: ['Design Principles', 'Typography', 'Minimalism', 'UI Tokens'],
    readingTime: 7,
    publishedAt: '2026-07-04T00:00:00.000Z',
    status: 'PUBLISHED',
    featured: true,
    seoTitle: 'The Art of Restraint: Purposeful UI Design — Gunjan Shrestha',
    seoDescription: 'Why subtractive interface design and typographic balance create timeless digital products.',
    content: `Every button, shadow, gradient, and floating badge added to an interface consumes cognitive bandwidth. In high-density software tools, decorative elements are not merely harmless additions; they are active distractions.

By anchoring our visual language in mathematically disciplined scales and deliberate neutrals, we allow the content itself to command attention.`,
    createdAt: '2026-07-01T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'post_5',
    title: 'Managing High-Value Physical Inventory: Bullion Accounting & Risk Safeguards',
    slug: 'managing-high-value-inventory-bullion-accounting',
    excerpt: 'An operational breakdown of vault safeguards, daily melt loss factors, and audit protocols when dealing with volatile precious metals assets.',
    coverImageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop',
    category: 'Finance & Operations',
    tags: ['Bullion', 'Inventory Management', 'Risk Auditing', 'Commerce'],
    readingTime: 9,
    publishedAt: '2026-08-10T00:00:00.000Z',
    status: 'PUBLISHED',
    featured: true,
    seoTitle: 'Managing High-Value Physical Inventory — Gunjan Shrestha',
    seoDescription: 'Operational disciplines and risk safeguards from precious metals bullion trade.',
    content: `When handling physical assets worth millions of rupees on a daily counter, operational discipline is the only difference between solvency and catastrophic loss.

From double-entry weighing checkpoints to karat purity standardization and vault reconciliation, physical commodity management provides unbeatable lessons for risk-aware software architecture.`,
    createdAt: '2026-08-08T00:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  }
];

export const initialSocialLinks: SocialLink[] = [
  { id: 'soc_1', platform: 'LinkedIn', label: 'LinkedIn', url: 'https://www.linkedin.com/in/gunjan-shrestha-8a6597293/', icon: 'Linkedin', displayOrder: 1, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-27T00:00:00.000Z' },
  { id: 'soc_2', platform: 'Facebook', label: 'Facebook', url: 'https://www.facebook.com/Lucifr3r', icon: 'Facebook', displayOrder: 2, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-27T00:00:00.000Z' },
  { id: 'soc_3', platform: 'Instagram', label: 'Instagram', url: 'https://www.instagram.com/g.s.02/', icon: 'Instagram', displayOrder: 3, published: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-08-27T00:00:00.000Z' },
];

export const initialSiteSetting: SiteSetting = {
  id: 'setting_1',
  siteName: 'Gunjan Shrestha',
  siteDescription: 'Personal digital identity platform of Gunjan Shrestha. Combining Technology, Design and Business experience into one perspective.',
  canonicalUrl: 'https://gunjan.dev',
  logoUrl: '',
  faviconUrl: '',
  profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop',
  email: 'gunjanstha01@gmail.com',
  phone: '+977 9800000000',
  location: 'Kathmandu, Nepal',
  footerText: '© 2026 Gunjan Shrestha. Technology × Design × Business.',
  accentColor: '#c6a87d',
  maintenanceMode: false,
  analyticsEnabled: true,
  defaultSeoTitle: 'Gunjan Shrestha — Technology, Design & Business',
  defaultSeoDescription: 'Personal digital identity platform and professional profile of Gunjan Shrestha. Exploring technology, software, design, and business operations.',
  defaultOgImageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
  seoKeywords: 'Gunjan Shrestha, Technology, Systems Architecture, Design Systems, Business Operations, Nepal, Software Engineer',
  allowIndexing: true,
  googleSiteVerification: '',
  googleAnalyticsId: '',
  customHeadSnippet: '',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-08-26T00:00:00.000Z',
};

export const initialContactMessages: ContactMessage[] = [
  {
    id: 'msg_1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    subject: 'Consultation on Inventory Digitization for Gold Trade',
    message: 'Hello Gunjan, I came across your profile and noticed your background in both jewellery retail and software design. We operate a bullion and jewellery store in New Road and are looking to modernize our inventory and billing workflow. Would love to discuss a potential consultation.',
    status: 'NEW',
    ipHash: 'hash_8f9a2b',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    createdAt: '2026-08-20T14:30:00.000Z',
    updatedAt: '2026-08-20T14:30:00.000Z',
  },
  {
    id: 'msg_2',
    name: 'Priya Adhikari',
    email: 'priya.adhikari@designstudio.np',
    subject: 'Collaboration on High-End Brand & Web Interface',
    message: 'Hi Gunjan, loved your personal statement on systems over screens. We have a client launching a luxury artisanal lifestyle brand in Nepal and need an interface designer who understands both minimal aesthetics and backend data flows. Let us connect!',
    status: 'READ',
    ipHash: 'hash_3c1d4e',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    createdAt: '2026-08-15T09:15:00.000Z',
    updatedAt: '2026-08-16T11:00:00.000Z',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    userId: 'admin_1',
    userEmail: 'gunjanstha01@gmail.com',
    action: 'ADMIN_INITIALIZED',
    entityType: 'System',
    entityId: 'system_root',
    metadata: { note: 'Primary administrator established and security architecture locked.' },
    ipHash: '127.0.0.1_hash',
    createdAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'log_2',
    userId: 'admin_1',
    userEmail: 'gunjanstha01@gmail.com',
    action: 'EXPERIENCE_PUBLISHED',
    entityType: 'Experience',
    entityId: 'exp_1',
    metadata: { title: 'Information Technology' },
    ipHash: '127.0.0.1_hash',
    createdAt: '2026-08-26T00:05:00.000Z',
  },
  {
    id: 'log_3',
    userId: 'admin_1',
    userEmail: 'gunjanstha01@gmail.com',
    action: 'BLOG_PUBLISHED',
    entityType: 'BlogPost',
    entityId: 'post_1',
    metadata: { title: 'Why I Prefer Building Systems Over Screens' },
    ipHash: '127.0.0.1_hash',
    createdAt: '2026-08-26T00:10:00.000Z',
  }
];
